flow:
  input_dim: 2
  hidden_dim: 64
  hidden_layers: 5
  output_dim: 2
  nflows: 10
  learning_rate: 1e-5
  weight_decay: 1e-5
  device: cuda
  batch_size: 128
  epochs: 1000

triangular:
  input_dim: 2
  hidden_dim: 32
  hidden_layers: 4
  device: cuda
  weight_decay: 0
  batch_size: 128
  epochs: 100
  learning_rate: 5e-4